vector:
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 0.0.0.0:8686
      playground: true
    sources:
      mqtt:
        type: mqtt
        host: rmqtt
        port: 1883
        decoding:
          codec: json
        topic: sensors
    sinks:
      clickhouse:
        type: clickhouse
        inputs:
          - mqtt
        endpoint: http://clickstack-clickhouse:8123
        table: sensors
