clickstack:
  hyperdx:
    frontendUrl: https://clickhouse.limoj.de
    ingress:
      enabled: true
      ingressClassName:
      tls:
        enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: clickhouse.limoj.de
      path: / # Traefik does not support the regex default in PathPrefix
      pathType: Prefix
