apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmqtt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rmqtt
          image: rmqtt/rmqtt:latest
          ports:
            - name: mqtt
              containerPort: 1883
            - name: mqtts
              containerPort: 8883
            - name: cluster
              containerPort: 11883
            - name: api
              containerPort: 6060
