apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP

metadata:
  name: rmqtt

spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`rmqtt.limoj.de`)
      services:
        - name: rmqtt
          port: 1883
      tls:
        secretName: rmqtt-tls
