apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rmqtt

resources:
  - deployment.yaml
  - service.yaml
  - ingressroute-tcp.yaml
  - certificate.yaml

images:
  - name: rmqtt/rmqtt
    newName: docker.io/rmqtt/rmqtt
    newTag: 0.18.0

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: rmqtt
      app.kubernetes.io/version: 0.18.0
