apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rmqtt

commonLabels:
  app.kubernetes.io/name: rmqtt
  app.kubernetes.io/version: 0.18.1
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - ingressroute-tcp.yaml

images:
  - name: rmqtt/rmqtt
    newTag: 0.18.1
