apiVersion: v1
kind: Service
metadata:
  name: rmqtt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rmqtt
  ports:
    - port: 1883
      targetPort: mqtt
      name: mqtt-tcp
    - port: 8883
      targetPort: mqtts
      name: mqtt-tcp-tls
    - port: 11883
      targetPort: cluster
      name: mqtt-tcp-internal
    - port: 6060
      targetPort: api
      name: api
