config:
  inputs:
    mqtt_consumer:
      servers: ["tcp://rmqtt:1883"]
      topics: ["sensors/#"]
      data_format: influx

  outputs:
    influxdb:
      urls:
        - "http://victoriametrics-victoria-metrics-single-server:8428"
      database: demo
      timeout: "5s"
