apiVersion: v2
name: grafana
description: Wrapper chart for Grafana with Traefik IngressRoute
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 11.0.1
    repository: https://grafana-community.github.io/helm-charts
